"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CloudCheck, Download, LockKeyhole, LogOut, MessageSquare, RefreshCw, Settings2, ShieldCheck, Star, WifiOff } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { languageNames } from "@/lib/languages";
import { type Feedback, highlights, ratingLabels } from "@/lib/survey";
import { getSettings, readFeedback, syncFeedback, type QueuedFeedback } from "@/lib/local-store";

function downloadCSV(rows: Feedback[],name:string){
  const cell=(v:unknown)=>{let s=String(v??""); if(/^[\s]*[=+@\-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
  const fields=["id","createdAt","kioskId","kioskName","surveyVersion","language","overall","presentation","informative","highlights","other","recommendation","comment"] as const;
  const csv='\uFEFF'+[fields.join(","),...rows.map(r=>fields.map(f=>cell(Array.isArray(r[f])?(r[f] as string[]).join("; "):r[f])).join(","))].join("\r\n");
  const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);
}
export default function Staff(){
  const [signed,setSigned]=useState(false),[checking,setChecking]=useState(true),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[rows,setRows]=useState<Feedback[]>([]),[local,setLocal]=useState<QueuedFeedback[]>([]),[from,setFrom]=useState(""),[to,setTo]=useState(""),[notice,setNotice]=useState(""),[syncing,setSyncing]=useState(false),[name,setName]=useState(""),[timeout,setTimeoutValue]=useState("120"),[lastSync,setLastSync]=useState(""),[loaded,setLoaded]=useState(false);
  const active=useRef(Date.now());
  const loadLocal=useCallback(async()=>{setLocal(await readFeedback());setLastSync(localStorage.getItem("toyota-last-sync")||"");},[]);
  const logout=useCallback(async()=>{try{await fetch("/api/staff/session",{method:"DELETE"});}finally{setSigned(false);setRows([]);setLocal([]);setPassword("");setLoaded(false);}},[]);
  const load=useCallback(async()=>{
    setBusy(true);setError("");setLoaded(false);
    try{
      const collected:Feedback[]=[];let offset=0,more=true;
      while(more){const q=new URLSearchParams({offset:String(offset)});if(from)q.set("from",new Date(from+'T00:00:00').toISOString());if(to)q.set("to",new Date(to+'T23:59:59.999').toISOString());const res=await fetch('/api/staff/feedback?'+q);
        if(res.status===401){await logout();throw new Error("Your staff session expired. Please sign in again.");}
        const data=await res.json() as {error?:string;rows:Feedback[];nextOffset:number;more:boolean};if(!res.ok)throw new Error(data.error);collected.push(...data.rows);offset=data.nextOffset;more=data.more;
      }
      setRows(collected);await loadLocal();setLoaded(true);
    }catch(e){setError(e instanceof Error?e.message:"Couldn’t load feedback.");}finally{setBusy(false);}
  },[from,to,loadLocal,logout]);
  useEffect(()=>{fetch('/api/staff/session').then(r=>r.json() as Promise<{authorised:boolean}>).then(d=>setSigned(d.authorised)).catch(()=>setError("Connect to the internet to open staff access.")).finally(()=>setChecking(false));const s=getSettings();setName(s.name);setTimeoutValue(String(s.idleSeconds));},[]);
  useEffect(()=>{if(signed)void load();},[signed,load]);
  useEffect(()=>{if(!signed)return;active.current=Date.now();const touch=()=>{active.current=Date.now();};window.addEventListener("pointerdown",touch);window.addEventListener("keydown",touch);const timer=setInterval(()=>{if(Date.now()-active.current>300000)void logout();},10000);return()=>{clearInterval(timer);window.removeEventListener("pointerdown",touch);window.removeEventListener("keydown",touch);};},[signed,logout]);
  const average=rows.length?(rows.reduce((s,r)=>s+r.overall,0)/rows.length).toFixed(1):"—";
  const recommended=rows.filter(r=>r.recommendation!==null),yes=recommended.length?Math.round(recommended.filter(r=>r.recommendation==='yes').length/recommended.length*100):null;
  const pending=local.filter(r=>!r.syncedAt);
  const comments=useMemo(()=>rows.filter(r=>r.comment||r.other),[rows]);
  async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch('/api/staff/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error);setSigned(true);setPassword("");}catch(e){setError(e instanceof Error?e.message:"Unable to sign in.");}finally{setBusy(false);}}
  async function sync(){setSyncing(true);setNotice("");try{const result=await syncFeedback();await loadLocal();setNotice(result.error||"All feedback from this device is synced.");if(!result.error)await load();}catch{setNotice("Couldn’t sync. Feedback is still saved on this device.");}finally{setSyncing(false);}}
  return <div className="staff-shell"><header className="site-header"><a className="brand" href="/"><img className="toyota-logo" src="/toyota-logo.svg" alt="Toyota"/><span className="brand-divider"/><span className="brand-title">EXPERIENCE<br/>CENTRE</span></a><div className="header-right"><a className="back-button" href="/" onClick={()=>{if(signed)void logout();}}><ArrowLeft size={16}/> Back to kiosk</a>{signed&&<button className="back-button" onClick={logout}><LogOut size={16}/> Sign out</button>}</div></header>
  {!signed?<main className="staff-login"><div className="login-emblem"><LockKeyhole size={29}/></div><span className="eyebrow panel-eyebrow">FOR THE CENTRE TEAM</span><h1>A closer look<br/>at every visit<span>.</span></h1><p>Sign in to view feedback and manage this kiosk.</p><form onSubmit={login}><label className="field-label">Staff access key<input autoComplete="current-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="Enter your staff access key"/></label>{error&&<p className="error-message" role="alert">{error}</p>}<button className="primary-button" disabled={busy||checking}>{checking?"Checking access…":busy?"Signing in…":"Open staff dashboard"}<ArrowRight size={18}/></button></form><p className="login-help"><ShieldCheck size={14}/> Staff access is protected. Ask your kiosk administrator for the key.</p></main>:
  <main className="staff-main"><div className="dashboard-heading"><div><span className="eyebrow panel-eyebrow">LISTEN. LEARN. IMPROVE.</span><h1>Visitor insights<span>.</span></h1><p>Every voice helps move the experience forward.</p></div><button className="secondary-button" disabled={busy||!loaded} onClick={()=>downloadCSV(rows,`toyota-feedback-${new Date().toISOString().slice(0,10)}.csv`)}><Download size={16}/> Export feedback</button></div>
  <div className="filter-bar"><label>From<input type="date" value={from} max={to||undefined} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} min={from||undefined} onChange={e=>setTo(e.target.value)}/></label>{(from||to)&&<button className="back-button" onClick={()=>{setFrom("");setTo("");}}>Clear dates</button>}<button className="back-button" onClick={load} disabled={busy}><RefreshCw size={15} className={busy?"spin":""}/> {busy?"Loading…":"Refresh"}</button></div>
  {error&&<p className="error-message" role="alert">{error}</p>}
  <div className="stats-grid"><article><span>Responses</span><strong>{loaded?rows.length:"—"}</strong><small>{from||to?"In the selected date range":"All collected feedback"}</small></article><article><span>Overall experience</span><strong>{loaded?average:"—"}<em> / 5</em></strong><small>Average visitor rating</small></article><article><span>Would recommend</span><strong>{loaded&&yes!==null?yes+'%':"—"}</strong><small>{recommended.length} visitors answered</small></article></div>
  <Tabs defaultValue="overview" className="staff-tabs"><TabsList variant="line"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="comments">Comments ({comments.length})</TabsTrigger><TabsTrigger value="kiosk">This kiosk</TabsTrigger></TabsList>
  <TabsContent value="overview"><div className="insight-grid"><section className="insight-panel"><h2>How visits felt</h2><p>Overall experience ratings</p><div className="bar-list">{ratingLabels.map((label,i)=>{const count=rows.filter(r=>r.overall===i+1).length;return <div className="bar-row" key={label}><span>{label}</span><div className="bar-track"><div style={{width:`${rows.length?count/rows.length*100:0}%`}}/></div><strong>{count}</strong></div>;})}</div>{loaded&&!rows.length&&<p className="empty-hint">Your first visitor response will appear here.</p>}</section><section className="insight-panel"><h2>What stood out</h2><p>Visitors can choose more than one highlight</p><div className="bar-list">{highlights.map(label=>{const count=rows.filter(r=>r.highlights.includes(label)).length;return <div className="bar-row highlight-bar" key={label}><span>{label}</span><div className="bar-track"><div style={{width:`${rows.length?count/rows.length*100:0}%`}}/></div><strong>{count}</strong></div>;})}</div></section></div><section className="insight-panel latest-panel"><h2>Recent feedback</h2><div className="feedback-table-wrap"><table className="feedback-table"><thead><tr><th>Visit</th><th>Kiosk</th><th>Language</th><th>Overall</th><th>Recommend</th></tr></thead><tbody>{rows.slice(0,20).map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleString()}</td><td>{r.kioskName}</td><td lang={r.language}>{languageNames[r.language] || r.language}</td><td>{ratingLabels[r.overall-1]}</td><td>{r.recommendation||"Skipped"}</td></tr>)}</tbody></table></div>{loaded&&!rows.length&&<p className="empty-hint">No feedback in this date range.</p>}<p className="table-note">Showing the latest {Math.min(rows.length,20)} of {rows.length} responses. Export includes all filtered responses.</p></section></TabsContent>
  <TabsContent value="comments"><section className="insight-panel"><h2>In our visitors’ words</h2><p>Optional comments and other highlights</p>{!comments.length&&<div className="empty-comments"><MessageSquare size={30}/><h3>No comments yet</h3><p>Written feedback will appear here when visitors leave it.</p></div>}{comments.map(r=><article className="comment-card" key={r.id}><div><span>{ratingLabels[r.overall-1]} · {r.kioskName} · <span lang={r.language}>{languageNames[r.language] || r.language}</span></span><time>{new Date(r.createdAt).toLocaleDateString()}</time></div>{r.comment&&<p lang={r.language}>{r.comment}</p>}{r.other&&<p><strong>Other highlight:</strong> <span lang={r.language}>{r.other}</span></p>}</article>)}</section></TabsContent>
  <TabsContent value="kiosk"><div className="insight-grid"><section className="insight-panel"><div className="panel-icon-title">{pending.length?<WifiOff size={24}/>:<CloudCheck size={24}/>}<h2>Feedback on this device</h2></div><p>{pending.length?`${pending.length} responses waiting to sync`:`All ${local.length} local responses synced`}</p><p className="device-detail">Last successful sync: {lastSync?new Date(lastSync).toLocaleString():"No sync yet"}</p><p className="device-detail">Saved responses remain on this kiosk if the connection drops. Keep this browser’s site data to preserve unsynced feedback.</p><div className="device-actions"><button className="primary-button" onClick={sync} disabled={syncing}><RefreshCw size={16} className={syncing?"spin":""}/>{syncing?"Syncing…":"Sync now"}</button><button className="secondary-button" disabled={!local.length} onClick={()=>downloadCSV(local,`toyota-device-backup-${new Date().toISOString().slice(0,10)}.csv`)}><Download size={16}/> Local backup</button></div>{notice&&<p className="notice" role="status">{notice}</p>}</section><section className="insight-panel"><div className="panel-icon-title"><Settings2 size={24}/><h2>Kiosk settings</h2></div><label className="field-label">Device name<input maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field-label">Idle warning after<Select value={timeout} onValueChange={setTimeoutValue}><SelectTrigger className="timeout-select"><SelectValue/></SelectTrigger><SelectContent>{[60,120,180,300,600].map(s=><SelectItem value={String(s)} key={s}>{s/60} {s===60?"minute":"minutes"}</SelectItem>)}</SelectContent></Select></label><p className="device-detail">Visitors get a 30-second warning and can extend their time. Completed surveys reset after 10 seconds.</p><button className="primary-button settings-save" onClick={()=>{localStorage.setItem("toyota-settings",JSON.stringify({name:name.trim()||"Experience Centre · 01",idleSeconds:Number(timeout)}));setNotice("Kiosk settings saved on this device.");}}>Save settings <Check size={16}/></button></section></div></TabsContent></Tabs>
  <p className="staff-session-note"><LockKeyhole size={13}/> Staff sessions expire after 15 minutes, or 5 minutes without activity. Sign out before returning the kiosk to visitors.</p></main>}</div>;
}
