"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CloudCheck, Download, LockKeyhole, LogOut, MessageSquare, RefreshCw, Settings2, ShieldCheck, Star, WifiOff } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { languageNames } from "@/lib/languages";
import { type Feedback, highlights, ratingLabels } from "@/lib/survey";
import { loadStaffFeedback, StaffSessionExpired, feedbackCSV } from "@/lib/staff-results";
import { getSettings, readFeedback, syncFeedback, type QueuedFeedback } from "@/lib/local-store";

function downloadCSV(rows: Feedback[],name:string){
  const csv=feedbackCSV(rows);
  const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);
}
export default function Staff(){
  const [signed,setSigned]=useState(false),[checking,setChecking]=useState(true),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[rows,setRows]=useState<Feedback[]>([]),[local,setLocal]=useState<QueuedFeedback[]>([]),[from,setFrom]=useState(""),[to,setTo]=useState(""),[notice,setNotice]=useState(""),[syncing,setSyncing]=useState(false),[name,setName]=useState(""),[timeout,setTimeoutValue]=useState("120"),[lastSync,setLastSync]=useState(""),[loaded,setLoaded]=useState(false);
  const [localError,setLocalError]=useState(""),[localLoaded,setLocalLoaded]=useState(false),[loadedRange,setLoadedRange]=useState("");
  const active=useRef(Date.now()),request=useRef<AbortController|null>(null),localRequest=useRef(0),signedRef=useRef(signed);
  signedRef.current=signed;
  const rangeKey=from+"|"+to;
  const resultsReady=loaded&&loadedRange===rangeKey;
  const loadLocal=useCallback(async()=>{
    const generation=++localRequest.current;
    try{
      const records=await readFeedback();if(generation!==localRequest.current)return;
      setLocal(records);setLocalLoaded(true);setLocalError("");
      const latest=records.map(row=>row.syncedAt||"").sort().at(-1)||"";setLastSync(latest);
    }catch{if(generation===localRequest.current){setLocalLoaded(false);setLocalError("Device storage is unavailable. Server feedback is still shown; local backup and sync will be available when storage returns.");}}
  },[]);
  const logout=useCallback(async()=>{
    signedRef.current=false;request.current?.abort();localRequest.current++;
    setSigned(false);setRows([]);setLocal([]);setPassword("");setLoaded(false);setLocalLoaded(false);setBusy(false);
    try{await fetch("/api/staff/session",{method:"DELETE"});}catch{}
  },[]);
  const load=useCallback(async()=>{
    request.current?.abort();const current=new AbortController();request.current=current;
    setBusy(true);setError("");setLoaded(false);setRows([]);
    try{
      const collected=await loadStaffFeedback(from,to,current.signal);
      if(current.signal.aborted||request.current!==current)return;
      setRows(collected);setLoadedRange(from+"|"+to);setLoaded(true);
    }catch(e){
      if(current.signal.aborted||request.current!==current)return;
      if(e instanceof StaffSessionExpired)await logout();
      setError(e instanceof Error?e.message:"Couldn’t load feedback. Please try again.");
    }finally{if(request.current===current&&!current.signal.aborted)setBusy(false);}
  },[from,to,logout]);
  const latestLoad=useRef(load);latestLoad.current=load;
  useEffect(()=>{fetch('/api/staff/session').then(r=>r.json() as Promise<{authorised:boolean}>).then(d=>setSigned(d.authorised)).catch(()=>setError("Connect to the internet to open staff access.")).finally(()=>setChecking(false));const s=getSettings();setName(s.name);setTimeoutValue(String(s.idleSeconds));},[]);
  useEffect(()=>{if(signed)void load();return()=>request.current?.abort();},[signed,load]);
  useEffect(()=>{if(!signed)return;void loadLocal();const changed=()=>{void loadLocal();};window.addEventListener("feedback-change",changed);window.addEventListener("feedback-sync",changed);return()=>{localRequest.current++;window.removeEventListener("feedback-change",changed);window.removeEventListener("feedback-sync",changed);};},[signed,loadLocal]);
  useEffect(()=>{if(!signed)return;active.current=Date.now();const touch=()=>{active.current=Date.now();};window.addEventListener("pointerdown",touch);window.addEventListener("keydown",touch);const timer=setInterval(()=>{if(Date.now()-active.current>300000)void logout();},10000);return()=>{clearInterval(timer);window.removeEventListener("pointerdown",touch);window.removeEventListener("keydown",touch);};},[signed,logout]);
  const average=rows.length?(rows.reduce((s,r)=>s+r.overall,0)/rows.length).toFixed(1):"—";
  const recommended=rows.filter(r=>r.recommendation!==null),yes=recommended.length?Math.round(recommended.filter(r=>r.recommendation==='yes').length/recommended.length*100):null;
  const pending=local.filter(r=>!r.syncedAt);
  const comments=useMemo(()=>rows.filter(r=>r.comment||r.other),[rows]);
  async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch('/api/staff/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error);setSigned(true);setPassword("");}catch(e){setError(e instanceof Error?e.message:"Unable to sign in.");}finally{setBusy(false);}}
  async function sync(){setSyncing(true);setNotice("");try{const result=await syncFeedback();if(!signedRef.current)return;await loadLocal();setNotice(result.error||"All feedback from this device is synced.");if(!result.error)await latestLoad.current();}catch{if(signedRef.current)setNotice("Couldn’t sync. Feedback is still saved on this device.");}finally{setSyncing(false);}}
  return <div className="staff-shell"><header className="site-header"><a className="brand" href="/"><img className="toyota-logo" src="/toyota-logo.svg" alt="Toyota"/><span className="brand-divider"/><span className="brand-title">EXPERIENCE<br/>CENTRE</span></a><div className="header-right"><a className="back-button" href="/" onClick={()=>{if(signed)void logout();}}><ArrowLeft size={16}/> Back to kiosk</a>{signed&&<button className="back-button" onClick={logout}><LogOut size={16}/> Sign out</button>}</div></header>
  {!signed?<main className="staff-login"><div className="login-emblem"><LockKeyhole size={29}/></div><span className="eyebrow panel-eyebrow">FOR THE CENTRE TEAM</span><h1>A closer look<br/>at every visit<span>.</span></h1><p>Sign in to view feedback and manage this kiosk.</p><form onSubmit={login}><label className="field-label">Staff access key<input autoComplete="current-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="Enter your staff access key"/></label>{error&&<p className="error-message" role="alert">{error}</p>}<button className="primary-button" disabled={busy||checking}>{checking?"Checking access…":busy?"Signing in…":"Open staff dashboard"}<ArrowRight size={18}/></button></form><p className="login-help"><ShieldCheck size={14}/> Staff access is protected. Ask your kiosk administrator for the key.</p></main>:
  <main className="staff-main"><div className="dashboard-heading"><div><span className="eyebrow panel-eyebrow">LISTEN. LEARN. IMPROVE.</span><h1>Visitor insights<span>.</span></h1><p>Every voice helps move the experience forward.</p></div><button className="secondary-button" disabled={busy||!resultsReady} onClick={()=>downloadCSV(rows,`toyota-feedback-${new Date().toISOString().slice(0,10)}.csv`)}><Download size={16}/> Export feedback</button></div>
  <div className="filter-bar"><label>From<input type="date" value={from} max={to||undefined} onChange={e=>{request.current?.abort();setLoaded(false);setRows([]);setFrom(e.target.value);}}/></label><label>To<input type="date" value={to} min={from||undefined} onChange={e=>{request.current?.abort();setLoaded(false);setRows([]);setTo(e.target.value);}}/></label>{(from||to)&&<button className="back-button" onClick={()=>{request.current?.abort();setLoaded(false);setRows([]);setFrom("");setTo("");}}>Clear dates</button>}<button className="back-button" onClick={()=>void load()} disabled={busy}><RefreshCw size={15} className={busy?"spin":""}/> {busy?"Loading…":"Refresh"}</button></div>
  {error&&<p className="error-message" role="alert">{error}</p>}
  {busy&&<p className="staff-load-status" role="status"><RefreshCw size={18} className="spin"/> Loading the selected feedback…</p>}<div className="stats-grid" aria-busy={busy}><article><span>Responses</span><strong>{resultsReady?rows.length:"—"}</strong><small>{from||to?"In the selected date range":"All collected feedback"}</small></article><article><span>Overall experience</span><strong>{resultsReady?average:"—"}<em> / 5</em></strong><small>Average visitor rating</small></article><article><span>Would recommend</span><strong>{resultsReady&&yes!==null?yes+'%':"—"}</strong><small>{recommended.length} visitors answered</small></article></div>
  <Tabs defaultValue="overview" className="staff-tabs"><TabsList variant="line"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="comments">Comments ({comments.length})</TabsTrigger><TabsTrigger value="kiosk">This kiosk</TabsTrigger></TabsList>
  <TabsContent value="overview"><div className="insight-grid"><section className="insight-panel"><h2>How visits felt</h2><p>Overall experience ratings</p><div className="bar-list">{ratingLabels.map((label,i)=>{const count=rows.filter(r=>r.overall===i+1).length;return <div className="bar-row" key={label}><span>{label}</span><div className="bar-track"><div style={{width:`${rows.length?count/rows.length*100:0}%`}}/></div><strong>{count}</strong></div>;})}</div>{resultsReady&&!rows.length&&<p className="empty-hint">{from||to?"No responses in this date range. Try a wider range.":"Your first visitor response will appear here."}</p>}</section><section className="insight-panel"><h2>What stood out</h2><p>Visitors can choose more than one highlight</p><div className="bar-list">{highlights.map(label=>{const count=rows.filter(r=>r.highlights.includes(label)).length;return <div className="bar-row highlight-bar" key={label}><span>{label}</span><div className="bar-track"><div style={{width:`${rows.length?count/rows.length*100:0}%`}}/></div><strong>{count}</strong></div>;})}</div></section></div><section className="insight-panel latest-panel"><h2>Recent feedback</h2><div className="feedback-table-wrap"><table className="feedback-table"><thead><tr><th>Visit</th><th>Kiosk</th><th>Language</th><th>Overall</th><th>Recommend</th></tr></thead><tbody>{rows.slice(0,20).map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleString()}</td><td>{r.kioskName}</td><td lang={r.language}>{languageNames[r.language] || r.language}</td><td>{ratingLabels[r.overall-1]}</td><td>{r.recommendation||"Skipped"}</td></tr>)}</tbody></table></div>{resultsReady&&!rows.length&&<p className="empty-hint">No feedback in this date range.</p>}<p className="table-note">Showing the latest {Math.min(rows.length,20)} of {rows.length} responses. Export includes all filtered responses.</p></section></TabsContent>
  <TabsContent value="comments"><section className="insight-panel"><h2>In our visitors’ words</h2><p>Optional comments and other highlights</p>{resultsReady&&!comments.length&&<div className="empty-comments"><MessageSquare size={30}/><h3>No comments yet</h3><p>Written feedback will appear here when visitors leave it.</p></div>}{comments.map(r=><article className="comment-card" key={r.id}><div><span>{ratingLabels[r.overall-1]} · {r.kioskName} · <span lang={r.language}>{languageNames[r.language] || r.language}</span></span><time>{new Date(r.createdAt).toLocaleDateString()}</time></div>{r.comment&&<p lang={r.language}>{r.comment}</p>}{r.other&&<p><strong>Other highlight:</strong> <span lang={r.language}>{r.other}</span></p>}</article>)}</section></TabsContent>
  <TabsContent value="kiosk"><div className="insight-grid"><section className="insight-panel"><div className="panel-icon-title">{pending.length?<WifiOff size={24}/>:<CloudCheck size={24}/>}<h2>Feedback on this device</h2></div><p>{!localLoaded?"Checking this device’s saved feedback…":pending.length?`${pending.length} responses saved on this device, waiting to send`:local.length?`All ${local.length} local responses received by the server`:"No feedback saved on this device yet"}</p>{localError&&<div><p className="error-message" role="alert">{localError}</p><button className="secondary-button" onClick={()=>void loadLocal()}>Retry device storage</button></div>}<p className="device-detail">Last successful sync: {lastSync?new Date(lastSync).toLocaleString():"No sync yet"}</p><p className="device-detail">Saved responses remain on this kiosk if the connection drops. Keep this browser’s site data to preserve unsynced feedback.</p><div className="device-actions"><button className="primary-button" onClick={sync} disabled={syncing||!localLoaded}><RefreshCw size={16} className={syncing?"spin":""}/>{syncing?"Syncing…":"Sync now"}</button><button className="secondary-button" disabled={!localLoaded||!local.length} onClick={()=>downloadCSV(local,`toyota-device-backup-${new Date().toISOString().slice(0,10)}.csv`)}><Download size={16}/> Local backup</button></div>{notice&&<p className="notice" role="status">{notice}</p>}</section><section className="insight-panel"><div className="panel-icon-title"><Settings2 size={24}/><h2>Kiosk settings</h2></div><label className="field-label">Device name<input maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field-label">Idle warning after<Select value={timeout} onValueChange={setTimeoutValue}><SelectTrigger className="timeout-select"><SelectValue/></SelectTrigger><SelectContent>{[60,120,180,300,600].map(s=><SelectItem value={String(s)} key={s}>{s/60} {s===60?"minute":"minutes"}</SelectItem>)}</SelectContent></Select></label><p className="device-detail">Visitors get a 30-second warning and can extend their time. Completed surveys reset after 10 seconds.</p><button className="primary-button settings-save" onClick={()=>{localStorage.setItem("toyota-settings",JSON.stringify({name:name.trim()||"Experience Centre · 01",idleSeconds:Number(timeout)}));setNotice("Kiosk settings saved on this device.");}}>Save settings <Check size={16}/></button></section></div></TabsContent></Tabs>
  <p className="staff-session-note"><LockKeyhole size={13}/> Staff sessions expire after 15 minutes, or 5 minutes without activity. Sign out before returning the kiosk to visitors.</p></main>}</div>;
}
